### ISSUE TITLE
Get rid of `replace k8s.io/client-go => k8s.io/client-go v0.28.2`

### ISSUE THREAD

**Issue by omertuc** [openshift-kni/lifecycle-agent#269]
This makes importing LCA as a library (e.g. in image-based-install-operator) annoying as they have to copy our replace directives

**Comment by donpenney** [comment]
Unfortunately, there's an old pinning of client.go in open-cluster-management.io/config-policy-controller that pinned the version of client-go to v12.0.0+incompatible:
https://github.com/open-cluster-management-io/config-policy-controller/blob/v0.12.0/go.mod#L21

They've updated this in "main", so I think we should be able to drop this once they've got a new release.

/cc @jc-rh

**Comment by omertuc** [comment]
Yeah, I've gone down that rabbit hole and reached that same conclusion, should've documented that, sorry
